# Generated by Django 2.1.3 on 2018-11-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=30)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('healthcard', models.CharField(db_column='healthcard', max_length=20)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=13, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
    ]
