CREATE TABLE STAFF (
ID CHAR(8) NOT NULL,
Email VARCHAR(30) NOT NULL,
Name VARCHAR(20) NOT NULL,
License CHAR(8) NOT NULL,
Phone CHAR(13) NULL,
PRIMARY KEY (ID));
 
CREATE TABLE DOCTOR (
ID  CHAR(8) NOT NULL,
AvailableForEmergency  BIT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES STAFF(ID)
          ON DELETE CASCADE);
 
CREATE TABLE GeneralPracticioner (
ID CHAR(8) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES DOCTOR(ID)
          ON DELETE CASCADE);


CREATE TABLE Specialist (
ID CHAR(8) NOT NULL,
SPECIALIZATION VARCHAR(20) NULL,
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES DOCTOR(ID)
          ON DELETE CASCADE);
CREATE TABLE Nurse (
ID CHAR(8) NOT NULL,
DID CHAR(8) NOT NULL,
PRIMARY KEY (ID, DID),
FOREIGN KEY (ID) REFERENCES STAFF(ID)
ON DELETE CASCADE,
FOREIGN KEY (DID) REFERENCES DOCTOR(ID)
ON DELETE CASCADE);
 
 
CREATE TABLE Lab_Technician (
ID CHAR(8) NOT NULL,
FID CHAR(8) NOT NULL,
PRIMARY KEY (ID, FID),
FOREIGN KEY (ID) REFERENCES STAFF(ID)
ON DELETE CASCADE,
FOREIGN KEY (FID) REFERENCES Facility(ID) 
ON DELETE CASCADE);
 
CREATE TABLE Facility (
ID CHAR(8) NOT NULL,
Type VARCHAR(20) NOT NULL, 
PRIMARY KEY (ID));
 


 
CREATE TABLE WeeklySchedule (
ID CHAR(8) NOT NULL,
SID CHAR(8) NOT NULL,
PRIMARY KEY (ID),                                            
FOREIGN KEY (SID) REFERENCES Staff(ID)
ON DELETE CASCADE,
UNIQUE(SID));
 
CREATE TABLE Scheduled_Time (
Date DATE NOT NULL,
StartTime TIME NOT NULL,
EndTime TIME NOT NULL,
WID CHAR(8) NOT NULL,
Notes VARCHAR(60) NULL,
PRIMARY KEY (Date, StartTime, EndTime, WID),
FOREIGN KEY (WID) REFERENCES WeeklySchedule(ID)
ON DELETE CASCADE);
 
CREATE TABLE Books (
FID CHAR(8) NOT NULL,
AppointmentID CHAR(10) NOT NULL,
PRIMARY KEY (FID, AppointmentID),
FOREIGN KEY (FID) REFERENCES Facility(ID), 
FOREIGN KEY (AppointmentID) REFERENCES Appointment(AppointmentID));
 
 
CREATE TABLE Appointment (
AppointmentID CHAR(10) NOT NULL,
Date DATE NOT NULL,
Time TIME NOT NULL,
PID CHAR(8) NOT NULL,
DID CHAR(8) NOT NULL, 
PRIMARY KEY (AppointmentID, PID, DID),
FOREIGN KEY (PID) REFERENCES Patient(ID)
          ON DELETE CASCADE,
FOREIGN KEY (DID) REFERENCES Doctor(ID)
          ON DELETE CASCADE); 


CREATE TABLE Treats (
DID CHAR(8) NOT NULL,
PID CHAR(8) NOT NULL,
PrescriptionID CHAR(8) NOT NULL,
PRIMARY KEY (DID, PID, PrescriptionID),
FOREIGN KEY (DID) REFERENCES Doctor(ID),
FOREIGN KEY (PID) REFERENCES Patient(ID),
FOREIGN KEY (PrescriptionID) REFERENCES Prescription(PrescriptionID));
 
CREATE TABLE Patient (
ID CHAR(8) NOT NULL,
Email CHAR(30) NOT NULL,
Name CHAR(20) NOT NULL,
HealthCard VARCHAR(20) NOT NULL,
Phone CHAR(13) NULL,
PRIMARY KEY (ID));
CREATE TABLE Prescription (
PrescriptionID CHAR(8) NOT NULL,
INSTRUCTION VARCHAR(30) NULL,
Substitutable BIT NULL,
PRIMARY KEY (PrescriptionID));
 
CREATE TABLE Contains (
PrescriptionID CHAR(8) NOT NULL,
DIN CHAR(8) NOT NULL,
PRIMARY KEY (PrescriptionID, DIN),
FOREIGN KEY (PrescriptionID) REFERENCES Prescription(PrescriptionID),
FOREIGN KEY (DIN) REFERENCES Medicine(DIN));
 
CREATE TABLE Medicine (
DIN CHAR(8) NOT NULL,
Brand VARCHAR(20) NOT NULL,
Ingredients VARCHAR(20) NULL,
Side Effect VARCHAR(80) NULL,
PRIMARY KEY (DIN));