# Generated by Django 2.1.3 on 2018-11-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTime',
            fields=[
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('starttime', models.TimeField(db_column='starttime')),
                ('endtime', models.TimeField(db_column='endtime')),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=60, null=True)),
            ],
            options={
                'db_table': 'scheduled_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weeklyschedule',
            fields=[
                ('id', models.CharField(db_column='id', max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'weeklyschedule',
                'managed': False,
            },
        ),
    ]
