# Generated by Django 2.1.3 on 2018-11-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentid', models.AutoField(db_column='appointmentid', max_length=8, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('time', models.TimeField(db_column='time')),
            ],
            options={
                'db_table': 'appointment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.CharField(db_column='id', max_length=8, primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=20)),
            ],
            options={
                'db_table': 'facility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('din', models.CharField(db_column='din', max_length=8, primary_key=True, serialize=False)),
                ('brand', models.CharField(db_column='brand', max_length=20)),
                ('ingredients', models.CharField(blank=True, db_column='ingredients', max_length=20, null=True)),
                ('sideeffect', models.CharField(blank=True, db_column='sideeffects', max_length=80, null=True)),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionid', models.AutoField(db_column='prescriptionid', primary_key=True, serialize=False)),
                ('instruction', models.CharField(blank=True, db_column='instruction', max_length=30, null=True)),
                ('substitutable', models.BooleanField(blank=True, db_column='substitutable', null=True)),
            ],
            options={
                'db_table': 'prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=30)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('license', models.CharField(db_column='license', max_length=8)),
                ('phone', models.CharField(blank=True, db_column='phone', max_length=13, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('fid', models.ForeignKey(db_column='FID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Staff.Facility')),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contains',
            fields=[
                ('prescriptionid', models.ForeignKey(db_column='prescriptionid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Staff.Prescription')),
            ],
            options={
                'db_table': 'contains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Staff.Staff')),
                ('availableforemergency', models.BooleanField(db_column='availableforemergency', null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Staff.Staff')),
            ],
            options={
                'db_table': 'lab_technician',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Staff.Staff')),
            ],
            options={
                'db_table': 'nurse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generalpracticioner',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Staff.Doctor')),
            ],
            options={
                'db_table': 'generalpracticioner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Staff.Doctor')),
                ('specialization', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'specialist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treats',
            fields=[
                ('did', models.ForeignKey(db_column='did', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Staff.Doctor')),
            ],
            options={
                'db_table': 'treats',
                'managed': False,
            },
        ),
    ]
