# Generated by Django 2.1.3 on 2018-11-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='Books',
        ),
    ]
